"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import {
  ArrowRight,
  CalendarClock,
  ChevronDown,
  Handshake,
  Lock,
  MessageCircle,
  Search,
  Shirt,
  Star,
  X,
} from "lucide-react";
import { Chip } from "@/components/ui/primitives";

type Item = { id: string; q: string; a: string };
type Group = {
  id: string;
  label: string;
  icon: typeof Shirt;
  items: Item[];
};

const GROUPS: Group[] = [
  {
    id: "donating",
    label: "Donating",
    icon: Shirt,
    items: [
      {
        id: "what-can-i-donate",
        q: "What can I donate?",
        a: "Clothes, books, shoes, bags, toys and household extras — bedding, kitchenware, stationery, small linen. If it is clean, complete and still usable, it qualifies. We cannot take medicine, food, anything with exposed wiring, or items so damaged that only a recycler can use them.",
      },
      {
        id: "condition",
        q: "What condition does my stuff need to be in?",
        a: "Four buckets when you list an item: Like New, Good, Usable and Needs Repair. “Usable” is the most common one — a shirt with a soft collar or a workbook with pages written in is perfectly fine. What fails is mould, stains through the fabric, or missing parts that make something unsafe.",
      },
      {
        id: "minimum",
        q: "Is there a minimum or maximum quantity?",
        a: "No minimum. Six books or one jacket is a real donation and we will schedule it. There is no maximum either — above 50 items we split the bundle across two slots so the volunteer can carry it safely. Below 5 items, a drop-off hub is often quicker for everyone.",
      },
      {
        id: "not-accepted",
        q: "What happens if my items are not accepted?",
        a: "A partner can decline something at the hub, usually for condition or because nobody nearby needs it. Your donation gets a plain note (“shoes heavily worn at the sole”), no stars are credited, and we offer a return or a responsible recycler within seven days at our cost. A rejected item never disappears without a line in your timeline.",
      },
    ],
  },
  {
    id: "pickup",
    label: "Pickup & verification",
    icon: CalendarClock,
    items: [
      {
        id: "how-pickup-works",
        q: "How does doorstep pickup work?",
        a: "Choose Pickup in the donation wizard and pick a two-hour slot between 8 AM and 8 PM. A volunteer is assigned, calls before arriving, collects the sealed bundle and the handover is photographed into your timeline. Slots run seven days a week in Bengaluru, Mumbai, Pune and Delhi NCR.",
      },
      {
        id: "not-home",
        q: "What if I am not home during the slot?",
        a: "Write the donation code on the bag, leave it with your guard or a neighbour, and note that in the wizard — the volunteer will collect it without you. If plans change, reschedule free up to two hours before the slot from My Donations, or call +91 80 4711 2200 and we will move it for you.",
      },
      {
        id: "verification-time",
        q: "How long does verification take?",
        a: "The verification desk reviews photos and counts within 24 hours of the bundle reaching the partner hub. January and August are our heaviest months and can stretch to 48 hours. Your Impact Stars are credited the moment verification passes — never while the donation is still in review.",
      },
      {
        id: "proof",
        q: "How do I know the donation actually happened?",
        a: "Every donation carries a code, for example RK-2481. Its timeline shows Submitted, Pickup scheduled, Collected, Verified and Distributed, with the partner's name, the counts they logged and the distribution note. The public totals on the Transparency dashboard are built from exactly those records.",
      },
    ],
  },
  {
    id: "stars",
    label: "Impact Stars",
    icon: Star,
    items: [
      {
        id: "stars-calc",
        q: "How are Impact Stars calculated?",
        a: "Per item, after a partner verifies the count: clothes 10, books 8, shoes 20 a pair, bags 15, toys 12. “Other” items are reviewed by hand and credited case by case. Stars are never generated by the form — a human confirms the items first, then the ledger entry is written.",
      },
      {
        id: "stars-value",
        q: "Do Stars expire? Can I cash them out?",
        a: "Stars never expire, and they are not money. They are recognition with a permanent ledger behind them: they move you up levels, unlock listed perks — digital impact cards, local drop-off drives, quarterly reports, partner offers — and can be spent on those perks. They are not redeemable for cash unless a specific offer says so in writing.",
      },
      {
        id: "levels",
        q: "What are the levels and what do I get?",
        a: "Starter (0–499) gets a digital impact card. Contributor (500–1,999) gets early access to local collection drives. Community Builder (2,000–4,999) gets a quarterly impact report and partner shout-outs. Impact Champion (5,000+) gets reward-partner offers and an invite to our community ambassador programme.",
      },
    ],
  },
  {
    id: "account",
    label: "Account & privacy",
    icon: Lock,
    items: [
      {
        id: "need-account",
        q: "Do I need an account to donate?",
        a: "Yes — for pickups and drop-offs alike. The receipt, the pickup slot and your stars have to attach to someone, and a partner's confirmation needs a place to land. Sign-in takes ten seconds with a magic link or Google, and there is no password to invent or remember.",
      },
      {
        id: "data-use",
        q: "What do you do with my address and my photos?",
        a: "Your address is used to plan the pickup and to reach you if a volunteer is running late — nothing else. Photos are used to verify condition and quantity, then shown on your own donation timeline and to the partner receiving it. We do not sell either, and they never appear publicly. The full detail sits in our Privacy Policy.",
      },
      {
        id: "delete-account",
        q: "How do I delete my account and my data?",
        a: "Write to help@rekindle.org from the email address on your account and say “delete my account”. We remove your profile, address, donation photos and message history within 30 days and send you a confirmation. We keep only the minimal transaction records the law requires, flagged clearly in that confirmation mail.",
      },
    ],
  },
  {
    id: "partners",
    label: "Partners",
    icon: Handshake,
    items: [
      {
        id: "ngo-join",
        q: "How does an NGO join ReKindle?",
        a: "Apply from the partners page with your registration certificate, PAN, an address proof, a needs list and one contact person. We run a reference call and verify everything within ten working days, publish your profile, and route the first pickups. There is no fee, now or later — partners never pay to receive.",
      },
      {
        id: "partner-genuine",
        q: "How do I know a partner is genuine?",
        a: "Every verified badge is backed by document checks and a reference call. Each public profile shows the date we verified it, the items it currently needs, and what it has distributed so far. If a partner misses two reporting cycles, we pause new listings until they catch up — the badge is only as good as the reporting behind it.",
      },
      {
        id: "unusable-items",
        q: "Where do items that cannot be reused go?",
        a: "Partners try repair first — a button, a sole, a seam — and only then downcycle into rags, stuffing or fibre through authorised recyclers. What is genuinely unusable goes to licensed waste handlers, never to an open dump by our hand, and those quantities appear in the quarterly impact numbers.",
      },
    ],
  },
];

const TOTAL = GROUPS.reduce((sum, group) => sum + group.items.length, 0);

export function FaqExplorer() {
  const [query, setQuery] = useState("");
  const [active, setActive] = useState("all");
  const [open, setOpen] = useState<string[]>(["what-can-i-donate"]);

  const term = query.trim().toLowerCase();

  const groups = useMemo(() => {
    return GROUPS.filter((group) => active === "all" || group.id === active)
      .map((group) => ({
        ...group,
        items: group.items.filter(
          (item) =>
            !term ||
            item.q.toLowerCase().includes(term) || item.a.toLowerCase().includes(term),
        ),
      }))
      .filter((group) => group.items.length > 0);
  }, [term, active]);

  const shown = groups.reduce((sum, group) => sum + group.items.length, 0);

  function toggle(id: string) {
    setOpen((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  }

  return (
    <div>
      {/* search + filters */}
      <div className="surface-card p-5 sm:p-6">
        <div className="relative">
          <Search
            className="pointer-events-none absolute top-1/2 left-4 h-4 w-4 -translate-y-1/2 text-muted"
            aria-hidden
          />
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search questions — try “pickup”, “stars”, “delete”"
            aria-label="Search questions"
            className="w-full rounded-xl border border-line-strong bg-white py-3.5 pr-11 pl-11 text-[0.95rem] text-ink placeholder:text-muted/70 transition-colors focus:border-forest focus:outline-none focus:ring-4 focus:ring-mint"
          />
          {query && (
            <button
              type="button"
              onClick={() => setQuery("")}
              aria-label="Clear search"
              className="absolute top-1/2 right-3 -translate-y-1/2 rounded-full p-1.5 text-muted transition-colors hover:bg-sand hover:text-ink"
            >
              <X className="h-4 w-4" />
            </button>
          )}
        </div>

        <div className="mt-4 flex flex-wrap gap-2 pb-1">
          <Chip active={active === "all"} onClick={() => setActive("all")}>
            All
            <span
              className={`rounded-full px-1.5 text-[0.7rem] ${active === "all" ? "bg-white/15" : "bg-sand text-muted"}`}
            >
              {TOTAL}
            </span>
          </Chip>
          {GROUPS.map((group) => (
            <Chip key={group.id} active={active === group.id} onClick={() => setActive(group.id)}>
              <group.icon className="h-4 w-4" />
              {group.label}
              <span
                className={`rounded-full px-1.5 text-[0.7rem] ${active === group.id ? "bg-white/15" : "bg-sand text-muted"}`}
              >
                {group.items.length}
              </span>
            </Chip>
          ))}
        </div>

        <p className="mt-4 text-xs font-semibold text-muted" role="status">
          Showing {shown} of {TOTAL} questions
          {term && (
            <>
              {" "}
              matching <span className="font-bold text-ink-soft">“{query.trim()}”</span>
            </>
          )}
          {active !== "all" && (
            <> · in {groups.find((g) => g.id === active)?.label ?? "this group"}</>
          )}
        </p>
      </div>

      {/* answers */}
      {shown === 0 ? (
        <div className="surface-card mt-6 flex flex-col items-center px-6 py-14 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-sand text-ink-soft">
            <Search className="h-6 w-6" strokeWidth={1.8} />
          </span>
          <h3 className="mt-4 text-lg font-bold text-ink">
            Nothing matches “{query.trim() || "that filter"}”
          </h3>
          <p className="mt-2 max-w-sm text-sm leading-relaxed text-muted">
            Shorter words work better — or ask us directly and a human will reply within a working
            day.
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <button
              type="button"
              onClick={() => {
                setQuery("");
                setActive("all");
              }}
              className="rounded-xl border border-line-strong bg-white px-5 py-2.5 text-sm font-bold text-ink-soft transition-colors hover:border-forest hover:text-forest"
            >
              Clear search & filters
            </button>
            <Link
              href="/contact"
              className="inline-flex items-center gap-1.5 rounded-xl bg-forest px-5 py-2.5 text-sm font-bold text-cream transition-colors hover:bg-forest-dark"
            >
              Ask a human
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      ) : (
        <div className="mt-8 space-y-10">
          {groups.map((group) => (
            <section key={group.id} aria-label={group.label}>
              <div className="flex items-center gap-3">
                <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-mint text-forest">
                  <group.icon className="h-4 w-4" strokeWidth={2} />
                </span>
                <h2 className="text-xs font-bold tracking-[0.2em] text-forest-soft uppercase">
                  {group.label}
                </h2>
                <span className="h-px flex-1 bg-line" aria-hidden />
                <span className="text-xs font-bold text-muted tabular-nums">{group.items.length}</span>
              </div>

              <ul className="mt-4 space-y-3">
                {group.items.map((item) => {
                  const isOpen = open.includes(item.id);
                  return (
                    <li key={item.id} className="surface-card overflow-hidden transition-colors hover:border-mint-deep">
                      <h3>
                        <button
                          type="button"
                          onClick={() => toggle(item.id)}
                          aria-expanded={isOpen}
                          aria-controls={`faq-${item.id}`}
                          className="flex w-full items-start gap-4 px-5 py-4 text-left sm:px-6 sm:py-5"
                        >
                          <span className="min-w-1 flex-1 text-[0.95rem] leading-snug font-extrabold text-ink sm:text-base">
                            {item.q}
                          </span>
                          <span
                            className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition-all duration-300 ${
                              isOpen ? "rotate-180 bg-forest text-cream" : "bg-sand text-ink-soft"
                            }`}
                            aria-hidden
                          >
                            <ChevronDown className="h-4 w-4" />
                          </span>
                        </button>
                      </h3>
                      <div
                        id={`faq-${item.id}`}
                        className={`grid transition-[grid-template-rows] duration-300 ease-out ${
                          isOpen ? "grid-rows-[1fr]" : "grid-rows-[0fr]"
                        }`}
                      >
                        <div className="overflow-hidden">
                          <p className="border-t border-line px-5 py-4 text-sm leading-relaxed text-muted sm:px-6 sm:pb-5">
                            {item.a}
                          </p>
                        </div>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </section>
          ))}
        </div>
      )}

      <div className="mt-10 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-mint-deep bg-mint px-5 py-4">
        <p className="inline-flex items-center gap-2 text-sm font-semibold text-forest">
          <MessageCircle className="h-4 w-4" />
          Still stuck? We answer within a working day.
        </p>
        <Link
          href="/contact"
          className="inline-flex items-center gap-1.5 text-sm font-bold text-forest underline underline-offset-4 transition-colors hover:text-forest-dark"
        >
          Contact support
          <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    </div>
  );
}
